### ISSUE TITLE
Add property decorators to be able to access private variables

### ISSUE THREAD

**Issue by alexandregallego** [alexandregallego/AlphaVantage_API_stock_analysis#7]

**Comment by pritthakkar** [comment]
Hello I would like to work on this can you provide more detail about it, please?

**Comment by alexandregallego** [comment]
Hi Prit, sure. If you go to CompanyAnalysis.py file, there are many variables like **self.__balance_sheet_df**, **self.__income_statement_df** that are starting with two double underscores which makes them only accessible from the definition of the class but not outside of it. I was thinking on creating property decorators to make them accessible even from outside the class definition. Do you think you could be able to deliver this today?
